/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#4cd7f6",
        "surface-container-high": "#262a34",
        "on-primary-container": "#00424f",
        "outline-variant": "#3d494c",
        "inverse-primary": "#00687a",
        "error-container": "#93000a",
        "on-surface": "#dfe2ef",
        "surface": "#0f131c",
        "outline": "#869397",
        "surface-bright": "#353943",
        "inverse-on-surface": "#2c303a",
        "surface-container-lowest": "#0a0e17",
        "on-error": "#690005",
        "on-secondary-fixed": "#002113",
        "on-surface-variant": "#bcc9cd",
        "on-tertiary-fixed-variant": "#930013",
        "error": "#ffb4ab",
        "inverse-surface": "#dfe2ef",
        "tertiary": "#ffb3ad",
        "surface-dim": "#0f131c",
        "on-primary-fixed-variant": "#004e5c",
        "secondary-fixed": "#6ffbbe",
        "surface-container-low": "#181b25",
        "tertiary-fixed": "#ffdad7",
        "on-primary-fixed": "#001f26",
        "surface-variant": "#31353f",
        "surface-container-highest": "#31353f",
        "on-primary": "#003640",
        "surface-container": "#1c1f29",
        "secondary-container": "#00a572",
        "on-tertiary": "#68000a",
        "secondary": "#4edea3",
        "primary": "#4cd7f6",
        "on-tertiary-fixed": "#410004",
        "secondary-fixed-dim": "#4edea3",
        "on-error-container": "#ffdad6",
        "background": "#0f131c",
        "primary-fixed-dim": "#4cd7f6",
        "on-background": "#dfe2ef",
        "tertiary-fixed-dim": "#ffb3ad",
        "primary-container": "#06b6d4",
        "tertiary-container": "#ff817a",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-container": "#00311f",
        "on-secondary": "#003824",
        "on-tertiary-container": "#7e000f",
        "primary-fixed": "#acedff"
      },
      fontFamily: {
        "telemetry-md": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "telemetry-sm": ["JetBrains Mono", "monospace"],
        "telemetry-lg": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "telemetry-md": ["13px", {"lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "label-caps": ["10px", {"lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "700"}],
        "body-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "headline-xl": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-xl-mobile": ["26px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "telemetry-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "500"}],
        "telemetry-lg": ["18px", {"lineHeight": "24px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-sm": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      },
      spacing: {
        "gutter": "0.75rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "margin": "1rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem"
      }
    }
  }
}
